### ISSUE TITLE
Azure Key Vault Support

### ISSUE THREAD

**Issue by vcsjones** [vcsjones/OpenVsixSignTool#31]
We should support signing with an Azure Key Vault Key.

1. We need to take a dependency on the Azure Key Vault NuGet package. It supports netstandard, so it shouldn't stand in the way of #18.

1. It needs to authenticate to Azure. As far as I can tell, there are two ways to do this:
     1. With a Client ID and a Client Secret. These would probably come over as command line options. `--azure-key-vault-client-id` and `--azure-key-vault-client-secret` (short forms to be provided)
     1. With a Client ID and a Client Certificate ([documented here](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-use-from-web-application)). We would accept `--azure-key-vault-client-id` and `--azure-key-vault-client-sha1` where the former is the client ID and the latter is the SHA1 thumbprint of the authentication certificate. Use `ClientAssertionCertificate` to authenticate.

1. It needs a way to identify the URL of the key vault, and the name of the key in the vault.
    1. Introduce `--azure-key-vault-url` to accept the URL of the key vault.
    1. Introduce `--azure-key-vault-certificate-name` to accept the name of the certificate in the vault.
Considerations:

1. Should this all be under the *sign* command, or is this a new command like *azuresign* or *keyvaultsign*?

1. Key Vault has good documentation on signing parameters, like using PKCS15 vs PSS, but it doesn't explicitly document the format of the signature. I'm assuming this going to match Windows, but we may need to re-compose the signature.

1. Key Vault has no support for ECDSA. We need to ensure the ECDSA code paths don't happen, and shouldn't, since you won't be able to use an ECDSA key.

**Comment by onovotny** [comment]
For No. 4, seems like it can provide the .cer file/contents of a certificate it manages: https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificate

**Comment by vcsjones** [comment]
So my approach was a bit backward. Makes sense now that I've had a chance to play with KeyVault (wow by the way).

The "input" to OVST should be the certificate, not the key. The key is a property off the certificate.

**Comment by vcsjones** [comment]
Crap code that seems to do the trick.

```chsarp
var client = new Microsoft.Azure.KeyVault.KeyVaultClient();
var cert = await client.GetCertificateAsync((string)null);
var certificate = new X509Certificate2(cert.Cer);
var key = await client.GetKeyAsync(cert.KeyIdentifier.Identifier);
if (!key.Key.KeyOps.Contains("sign"))
{
    //GO AWAY
}
var parameters = certificate.GetRSAPublicKey().ExportParameters(false);
if (!key.Key.N.SequenceEqual(parameters.Modulus) || !key.Key.E.SequenceEqual(parameters.Exponent))
{
    //GO AWAY
}
var resultTuple = await client.SignAsync(key.KeyIdentifier.Identifier, "RS256", someStuffToSign);
if (key.KeyIdentifier.Identifier != resultTuple.Kid)
{
    //GO AWAY
}
var signature = resultTuple.Result;
```
